### ISSUE TITLE
Auto upload to gdrive isn't working

### ISSUE THREAD

**Issue by amie33r** [shirooo39/MiXLab#4]
Hello, after the recent update in the notebook the auto upload to google drive isn't working, please fix it @shirooo39

**Comment by shirooo39** [comment]
Automatic upload has been removed, because I don't think that'd be useful.

Not to mention writing files directly to GDrive through the GDrive mount module could lead to file corruption (I've been there. Trust me, you don't want that to happen).

I highly recommend people to use rclone instead.
It may take a bit of time and there's some learning curve, but it's way better than using Colab's GDrive mount module.
